### ISSUE TITLE
feat: consider support inline-type in IfStatement

### ISSUE THREAD

**Issue by axetroy** [MartinJohns/vscode-inline-types#12]
### why will I need this feature?

because we often write such code:

```typescript
const arr: any[] = [];

if (arr) {
  // this block always run
}
```

The decorator can remind us, what type of the condition expression.

because condition should be a boolean, not an array or object.

Array and Object always equal true, even it's empty. It makes us confused.

![1](https://user-images.githubusercontent.com/9758711/38471631-49345926-3ba6-11e8-93ee-e0b51b48ca60.png)

### and it's useful to check some mistake

for example: 

**Wrong: Missing await**

![1](https://user-images.githubusercontent.com/9758711/38471702-777d4242-3ba7-11e8-9ab1-82776176dd78.png)

**Correct**

![1](https://user-images.githubusercontent.com/9758711/38471688-40526932-3ba7-11e8-97c3-25c457a1f8ff.png)

**Comment by MartinJohns** [comment]
I think a [tslint rule](https://github.com/palantir/tslint) would make more sense here. The rule could verify that expressions in if-blocks are of the type `boolean` or are a call to a _type-guard_ function. That way you could actually prevent compilation as part of your build chain and are not tied to an extension for a specific editor to prevent bugs. I'm not sure if such a rule already exists, but it wouldn't be hard to write.

**Comment by axetroy** [comment]
Yeah, you are right.
It's lint job, the extension should do its own job well.
