### ISSUE TITLE
Add option to not render types for arrow functions twice.

### ISSUE THREAD

**Issue by Olian04** [MartinJohns/vscode-inline-types#15]
This: 
```ts
const foo: (par: any): any = (par: any): any => {}
```
would turn into this: 
```ts
const foo = (par: any): any => {}
```

**Comment by MartinJohns** [comment]
I agree that it makes sense and I've added it as the default value. The types for arrow functions can be added again using the feature flag `inlineTypes.features.arrowFunctionVariable`.
