### ISSUE TITLE
Make type renders their own characters

### ISSUE THREAD

**Issue by Olian04** [MartinJohns/vscode-inline-types#16]
_"Make type renders their own characters instead of having them be attached to the previous character."_

As it is now if a type is defined as `const foo: string = 'Hi';` then moving cursor from here `const fo|o: string = 'Hi';` one step to the right will move the cursor all the way over there `const foo: string |= 'Hi';`. I purpose that it instead moved the cursor to here `const foo|: string = 'Hi';` and then if you moved once more to the right we would end up over there `const foo: string |= 'Hi';`

**Comment by MartinJohns** [comment]
Unfortunately this is a limitation of the VS Code extension API. I'm rendering the text using the CSS `before` and `after` `contentText` styles. This really annoys me too. :-(

I will check the upcoming VS Code updates to see if there's a better solution, but as for now: No solution available.

**Comment by Olian04** [comment]
@MartinJohns  Can't you inject a [Zero-width space](https://en.wikipedia.org/wiki/Zero-width_space) and then use that as an anchor point for the type?
