### ISSUE TITLE
Not working for types defined in libraries

### ISSUE THREAD

**Issue by cancerberoSgx** [MartinJohns/vscode-inline-types#18]
![image](https://user-images.githubusercontent.com/112746/42073505-939feda0-7b3d-11e8-821b-0df98dcd1bfa.png)

This is my tsconfig: 

```
{
  "compilerOptions": {
    "target": "es6",   
    "module": "commonjs", 
    "moduleResolution": "node",
    "lib": ["es2018", "dom"],
    "outDir": "./dist", 
    "rootDir": ".",
    "strict": true, 
    "strictNullChecks": false,
    "noImplicitAny": true,
  }, 
  "include": [
    "src"
  ]
}
```

**Comment by MartinJohns** [comment]
Unfortunately I can't reproduce this issue. Can you provide an example repository? What VS Code version are you using?

![image](https://user-images.githubusercontent.com/5269069/42239674-ed1891f0-7f04-11e8-9a39-8a2b7ab95763.png)
