### ISSUE TITLE
Decoration styles (default or overridden) are not applied when the effective type is `any`

### ISSUE THREAD

**Issue by Meligy** [MartinJohns/vscode-inline-types#22]
See here:
![image](https://user-images.githubusercontent.com/171637/52681213-263ef600-2f8f-11e9-86f1-8407accee857.png)

The highlighted types are coming from the extension not written in the file. I don't why they keep showing with white color. I can override color and opacity from config but it still won't affect these 2 as shown in the picture.

It's very weird because in the picture we can see only one of the types shown for a `const` is affected by this issue. The others are fine.

**Comment by Meligy** [comment]
It seems to be an issue whenever the type is shown as `any`.

Just now I noticed the issue also happens in the last line there (line 14) in the arrow function return type (in the 2nd time it shows it, which is a separate issue). 

![image](https://user-images.githubusercontent.com/171637/52683800-2099de00-2f98-11e9-8790-2975ef86cebe.png)


It was not highlight above because I didn't notice it before.

**Comment by ackvf** [comment]
OT: How do you actually override the color and opacity in config?
